#! /bin/bash

declare -g IF_NAME
declare -g IP_ADDR
declare -g NET_DOMAIN
declare -g ZONE

# The XML format for network devices does not have a description tag so this
# is here to facilitate testing and debugging of networks managed by libvirt
# See the docs for all the supported tags:
# https://libvirt.org/formatnetwork.html
if [[ ${MISC[0]} =~ "test" ]]; then
    DEBUG=1
    DRY_RUN=1
    echo "Debugging and dry-run enabled"
fi

##############################################################################
# Extract device data from tmp folder structure
##############################################################################

function load_config_data {
    echo "Reading data from the XML"
    local temp="${TMP_CONFIG_PATH}/hookData/network/bridge/name.val"
    if [[ -f "${temp}" && -s "${temp}" ]]; then
        IF_NAME="$(cat ${temp})"
    fi

    local temp="${TMP_CONFIG_PATH}/hookData/network/ip/address.val"
    if [[ -f "${temp}" && -s "${temp}" ]]; then
        IP_ADDR="$(cat ${temp})"
    fi

    local temp="${TMP_CONFIG_PATH}/hookData/network/domain/name.val"
    if [[ -f "${temp}" && -s "${temp}" ]]; then
        NET_DOMAIN="$(cat ${temp})"
    fi

    local temp="${TMP_CONFIG_PATH}/hookData/network/bridge/zone.val"
    if [[ -f "${temp}" && -s "${temp}" ]]; then
        ZONE="$(cat ${temp})"
    fi
} # End-load_config_data

##############################################################################
# Functions commonly used across multiple different types of hooks
##############################################################################

