#! /bin/bash

# set -x
# set -e

# Reads in all the functions defined in qemu.d/default/<hook_name>/<state_name>/
# Most of the functions not defined here or in default that are called here
# are likely defined there. If you want to override them, you can redefine
# them in a script here qemu.d/<vm_name>/<hook_name>/<state_name>/
source "${0%/network}/default" "${@}" "<" "/dev/stdin"
