#! /bin/bash

# set -x
# set -e

# Reads in all the functions defined in qemu.d/default/<hook_name>/<state_name>/
# Most of the functions not defined here or in default that are called here
# are likely defined there. If you want to override them, you can redefine
# them in a script here qemu.d/<vm_name>/<hook_name>/<state_name>/
source "${0%/qemu}/default" "${@}" "<" "/dev/stdin"

# Calls the relevant function based on the hook name and VM state
if [ -n "$(command -v "${HOOK_NAME}_${STATE_NAME}")" ]; then
    echo "--------------NEXT--------------" >> "${LOG_FILE}"
    echo "$(date): ${0} ${@}" >> "${LOG_FILE}"
    eval \"${HOOK_NAME}_${STATE_NAME}\" &>> "${LOG_FILE}"
else
    echo "ERROR: Function not found: ${HOOK_NAME/-/_}_${STATE_NAME}" >> "${LOG_FILE}"
    declare -F >> "${LOG_FILE}"
fi
